### ISSUE TITLE
setup_requires in setup.py?

### ISSUE THREAD

**Issue by bjodah** [safijari/pybind11-cmake#1]
Hi, great package, really useful!
I saw that your generated `setup.py` errors out when `pybind11_cmake` is not found, perhaps it could be added to setup_requires instead?

It does unfortunately mean that one needs to inspect `sys.argv` to determine if the command is one that builds the extension module (and then only conditionally import from pybind11_cmake). SciPy's `setup.py` does this for example with respect to pybind:
https://github.com/scipy/scipy/blob/master/setup.py

Just a thought.

EDIT: astropy does something similar as well: https://github.com/astropy/astropy/blob/master/setup.py

**Comment by safijari** [comment]
This is something that has confused me a great deal in the past. The astopy example looks interesting. I can certainly take a look at it though you seem to have a better understanding of it than I do. Do you mind submitting a PR instead?

**Comment by bjodah** [comment]
Sure, I gave it a shot in #2
